---
- name: Install firewalld
  yum:
    name: firewalld

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_open_ports }}"
